apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{.Values.LLMBaseGPTService.DNS}}-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.LLMBaseGPTService.DNS}}          # имя твоего Deployment
  minReplicas: {{.Values.LLMBaseGPTService.MinReplicas}}             # минимум подов
  maxReplicas: {{.Values.LLMBaseGPTService.MaxReplicas}}            # максимум подов
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{.Values.LLMBaseGPTService.CpuAverage}} # если средняя загрузка CPU >70%, HPA добавит реплики