# 1) SelfSigned Issuer (создаёт CA secret единожды)
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned
  namespace: cert-manager
spec:
  selfSigned: {}
---
# 2) CA Certificate (создаёт secret с CA keypair)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-ca
  namespace: cert-manager
spec:
  isCA: true
  commonName: "onprem-root-ca"
  secretName: cluster-ca-secret
  privateKey:
    algorithm: RSA
    size: 4096
  duration: 43800h # ~5 лет
  issuerRef:
    name: selfsigned
    kind: Issuer
---
# 3) ClusterIssuer, базирующийся на созданном CA
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: cluster-ca-secret
