apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: {{.Values.cluster.name}}
  namespace: {{.Values.namespace}}
  annotations:
    strimzi.io/kraft: {{.Values.kraft.status}}
    strimzi.io/node-pools: {{.Values.controller.status}}
spec:
  kafka:
    version: {{.Values.cluster.spec.version}}
    replicas: 3
    listeners:
      - name: plain
        port: {{.Values.cluster.spec.port}}
        type: {{.Values.cluster.spec.type}}
        tls: {{.Values.cluster.spec.tls}}
    resources:
      requests:
        cpu: "1"
        memory: "2Gi"
      limits:
        cpu: "2"
        memory: "4Gi"
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
  entityOperator:
    topicOperator:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"
    userOperator:
      resources:
        requests:
          cpu: "100m"
          memory: "256Mi"
        limits:
          cpu: "200m"
          memory: "512Mi"
