apiVersion: v1
kind: Service
metadata:
  name: ingress-nginx
  namespace: ingress-nginx
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: ingress-nginx
  ports:
    - name: http
      port: 80
      nodePort: {{.Values.Gateway.NodePort}}
    - name: https
      port: 443
      nodePort: {{.Values.Gateway.gRPCPort}}
